name: Scan Python 3.9 Image for Vulnerabilities

on:
  workflow_dispatch:

jobs:
  docker-vuln-scan:
    runs-on: ubuntu-latest
    name: Run Trivy Vulnerability Scanner
    steps:
      - name: Run Trivy Scan on python:3.9
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.9'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

