name: Scan Python 3.9 Image for Vulnerabilities

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: Trivy Docker Image Scan

    steps:
    - name: Checkout (dummy step, required by GitHub)
      uses: actions/checkout@v3

    - name: Run Trivy Scan with SARIF output
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'python:3.9'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload SARIF file to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif



